name: Sync branches with main

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "holoisme"
          git config user.email "yousseflaraki99@gmail.com"

      - name: Sync branches with main
        run: |
          branches=$(git branch -r | grep -v 'main\|HEAD' | sed 's/origin\///')
          for branch in $branches; do
            git checkout $branch
            git merge origin/main
            git push origin $branch
          done
