name: "Run Application Tests"

on:
  push:
    branches: [master, main, feature/*, refractor/*, test/*, bugfix/*]
  pull_request:
    branches: [master, main, feature/*, refractor/*, test/*, bugfix/*]


defaults:
  run:
    working-directory: ./edweiss-app

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3

        with:
          node-version: '18'
        
      - name: Install dependencies
        run: npm ci
      
      - name: Check Typescript compilation
        run: npm run tscheck
        
      - name: Test and coverage
        run: npm run test
        env:
          CI: true
        continue-on-error: true
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=SnowWhiteEPFL_edweiss
            -Dsonar.organization=snowwhiteepfl
            -Dsonar.sources=./edweiss-app/        
            -Dsonar.javascript.lcov.reportPaths=./edweiss-app/coverage/lcov.info
            -Dsonar.exclusions=**/node_modules/**,**/coverage/**,**/__test__/**,**/.expo/**,**/android/**,**/.gitignore,**/app.config.ts,**/babel.config.js,**/hooks/**,**/declarations.d.ts,**/eas.json,**/expo-env.d.ts,**/metro.config.js,**/metro.config.ts,**/package-lock.json,**/package.json,**/tsconfig.json
        if: always()

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./edweiss-app/coverage/**