name: "Run Application Tests"

on:
  push:
    branches: [master, main, feature/*, refractor/*]
  pull_request:
    branches: [master, main, feature/*, refractor/*]

defaults:
  run:
    working-directory: ./edweiss-app

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3

        with:
          node-version: '18'
        
      - name: Install dependencies
        run: npm ci
      
      - name: Check Typescript compilation
        run: npm run tscheck
      
      # - name: Run Jest tests
      #   run: npm test
      #   env:
      #     CI: true

        
      - name: Test and coverage
        run: npm run test
        env:
          CI: true
        continue-on-error: true

      - name: List coverage directory contents (debug)
        run: ls -R
        if: always()
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=SnowWhiteEPFL_edweiss
            -Dsonar.organization=snowwhiteepfl
            -Dsonar.exclusions=**/__test__/**
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov-report/lcov-info.txt
        if: always()

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/lcov-report/lcov-info.txt