name: "Run Application Tests"

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

defaults:
  run:
    working-directory: ./edweiss-app

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3

        with:
          node-version: '18'
        
      - name: Install dependencies
        run: npm ci
      
      - name: Check Typescript compilation
        run: npm run tscheck
      
      # - name: Run Jest tests
      #   run: npm test
      #   env:
      #     CI: true
        
      # # - name: Upload Jest test results
      # #   if: always()
      # #   uses: actions/upload-artifact@v3
      # #   with:
      # #     name: jest-results
      # #     path: test-results # You might need to configure Jest to output results to this path
      
      # - name: Generate Jest coverage report
      #   run: npm run test -- --coverage


      - name: Test and coverage
        run: npm run test --coverage
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.exclusions=**/__test__/**

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage